// src/components/footer.svelte
<footer class="bg-gray-950 px-4 py-6 text-white md:px-10 dark:bg-gray-800">
	<div class="container mx-auto flex flex-col items-center justify-between md:flex-row">
		<p class="mb-4 text-sm md:mb-0">© 2024 hanamimanga. All rights reserved.</p>
		<p class="mb-4 md:mb-0">
			Check out{" "}
			<a target="_blank" class="font-bold text-blue-400" href="https://anime.lapaii.dev/">
				mikanime
			</a>
			, the anime version of this website!
		</p>
		<nav class="flex items-center gap-4">
			<a class="hover:underline" href="/about"> About </a>
			<a class="hover:underline" href="/contact"> Contact </a>
			<a class="hover:underline" target="_blank" href="https://github.com/yorunoken/hanamimanga">
				GitHub
			</a>
		</nav>
	</div>
</footer>

// frontend/src/components/footer.tsx
import Link from "next/link";

export default function Footer() {
    return (
        <footer className="mt-auto">
            <div className="border-t lg:container mx-auto">
                <div className="px-4 justify-between  flex flex-col sm:flex-row h-16 items-center">
                    <span className="font-bold text-sm">
                        © 2024 Hanami Manga. All rights reserved.
                    </span>
                    <Link
                        href="https://anime.lapaii.dev"
                        target="_blank"
                        className="text-sm font-medium hover:underline"
                        prefetch={false}
                    >
                        Check out mikanime, the anime version of this website!
                    </Link>
                    <div className="flex items-center gap-4 text-sm">
                        <Link
                            href="/about"
                            className="hover:underline"
                            prefetch={false}
                        >
                            About
                        </Link>
                        <Link
                            href="/contact"
                            className="hover:underline"
                            prefetch={false}
                        >
                            Contact
                        </Link>
                        <Link
                            href="https://github.com/yorunoken/hanami-manga"
                            target="_blank"
                            className="hover:underline"
                            prefetch={false}
                        >
                            GitHub
                        </Link>
                    </div>
                </div>
            </div>
        </footer>
    );
}
