// src/routes/title/[uuid]/+page.svelte
<script lang="ts">
	import { getJSON } from "utils/request";
	import { page } from "$app/stores";
	import Footer from "components/footer.svelte";
	import Header from "components/header.svelte";
	import LeftButton from "components/chevronLeftIcon.svelte";
	import RightButton from "components/chevronRightIcon.svelte";
	import SvelteMarkdown from "svelte-markdown";
	import Pagination from "components/chapterPagePagination.svelte";
	import { onMount } from "svelte";

	export let data;

	const uuid = $page.params.uuid;
	const chaptersPerPage = 40;

	let chapterData: MangaChapterSearch;

	let currentPage = 1;
	let dummyChapters = Array.from({ length: chaptersPerPage }, (_, i) => 1 + i);

	async function fetchData() {
		chapterData = await fetch(
			`/api/proxy-chapter?manga=${uuid}&order[chapter]=desc&translatedLanguage[]=en&limit=${chaptersPerPage}&offset=${(currentPage - 1) * chaptersPerPage}`
		).then((res) => res.json());
	}

	onMount(async () => {
		await fetchData();
	});

	function incrementPage() {
		currentPage++;
		fetchData();
	}

	function decrementPage() {
		currentPage--;
		fetchData();
	}

	function setPage(pageNumber: number) {
		currentPage = pageNumber;
		fetchData();
	}
</script>

<div class="flex min-h-[100dvh] flex-col">
	<Header />
	<main class="flex-1 bg-gray-100 px-4 py-6 md:px-6 md:py-12 dark:bg-gray-900">
		<div class="mx-auto grid max-w-4xl grid-cols-1 gap-8 md:grid-cols-2">
			{#if !data.manga || !chapterData}
				<div>
					<img width={400} height={500} alt="Manga Cover" class="rounded-md shadow-lg" />
				</div>
				<div>
					<h1 class="mb-2 text-3xl font-bold">Yomi Yori</h1>
					<div class="mb-4 flex flex-wrap gap-2">
						<div class="bg-primary-500 rounded-md border px-3 py-1 text-sm text-white">Yuri</div>
					</div>
					<p class="mb-6 text-gray-700 dark:text-gray-400">Yuri girls mm</p>
					<div class="rounded-md bg-gray-200 p-4 dark:bg-gray-800">
						<h2 class="mb-4 text-xl font-bold">Chapters</h2>
						<div class="flex justify-between">
							<ul class="space-y-2">
								{#each dummyChapters.slice(0, 20) as chapter}
									<li>
										<p class="text-primary-500 hover:underline">
											Chapter {chapter}
										</p>
									</li>
								{/each}
							</ul>
							<ul class="space-y-2">
								{#each dummyChapters.slice(20, 40) as chapter}
									<li>
										<p class="text-primary-500 hover:underline">
											Chapter {chapter}
										</p>
									</li>
								{/each}
							</ul>
						</div>
					</div>
				</div>
			{:else}
				<div>
					<img
						src={`/api/proxy-image?url=https://mangadex.org/covers/${data.manga.data.id}/${data.manga.data.relationships.find((relationship) => relationship.type === "cover_art")?.attributes.fileName}`}
						width={400}
						height={500}
						alt="Manga Cover"
						class="rounded-md shadow-lg"
					/>
				</div>
				<div>
					<h1 class="mb-2 text-3xl font-bold">
						{data.manga.data.attributes.title.en ??
							data.manga.data.attributes.altTitles?.filter((altTitle) => altTitle.en)[0].en ??
							data.manga.data.attributes.title["ja-ro"] ??
							data.manga.data.attributes.title["ja"]}
					</h1>
					<div class="mb-4 flex flex-wrap gap-2">
						{#each data.manga.data.attributes.tags as tag}
							<div class="bg-primary-500 rounded-md border px-3 py-1 text-sm text-white">
								{tag.attributes.name.en}
							</div>
						{/each}
					</div>
					<p class="mb-6 text-gray-700 dark:text-gray-400">
						<SvelteMarkdown
							source={data.manga.data.attributes.description.en ?? "No description was provided."}
						/>
					</p>
					<div class="rounded-md bg-gray-200 p-4 dark:bg-gray-800">
						<div class="flex justify-between">
							<h2 class="mb-4 text-xl font-bold">Chapters</h2>
							<h2 class="mb-4 text-base">
								Page {currentPage}/{Math.ceil(chapterData.total / chaptersPerPage)}
							</h2>
						</div>
						<div class="flex justify-between rounded-md border">
							<ul class="mr-3 space-y-2 p-2">
								{#each chapterData.data.slice(0, 20) as chapter}
									<li>
										<a href={`/chapter/${chapter.id}`} class="text-primary-500 hover:underline">
											Chapter {chapter.attributes.chapter}
											{chapter.attributes.title ? " - " + chapter.attributes.title : ""}
										</a>
									</li>
								{/each}
							</ul>
							<ul class="ml-3 space-y-2 p-2">
								{#each chapterData.data.slice(20, 40) as chapter}
									<li>
										<a href={`/chapter/${chapter.id}`} class="text-primary-500 hover:underline">
											Chapter {chapter.attributes.chapter}
											{chapter.attributes.title ? " - " + chapter.attributes.title : ""}
										</a>
									</li>
								{/each}
							</ul>
						</div>
					</div>
					<div class="mt-4 flex items-center justify-center space-x-2">
						{#if currentPage > 1}
							<LeftButton on:click={decrementPage} />
						{/if}
						<Pagination {currentPage} totalChapters={chapterData.total} {setPage} />
						{#if currentPage < Math.ceil(chapterData.total / chaptersPerPage)}
							<RightButton on:click={incrementPage} />
						{/if}
					</div>
				</div>
			{/if}
		</div>
	</main>
	<Footer />
</div>

// frontend/src/app/manga/[uuid]/page.tsx
import Tags from "@/components/tags";
import { Metadata } from "next";
import { ChapterListSchema, MangaResponseSchema } from "@/types/schema";
import { BASE_URL } from "@/lib";
import Image from "next/image";
import Link from "next/link";
import ChapterList from "@/components/chapterList";
import { Button } from "@/components/ui/button";
import { Suspense } from "react";
import { MangaPageSkeleton } from "@/components/mangaPageSkeleton";

type Props = {
    params: { uuid: string };
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { data: manga } = (await fetch(
        `${BASE_URL}api/proxy/manga/${params.uuid}`,
        { next: { revalidate: 60 * 60 } },
    ).then((response) => response.json())) as MangaResponseSchema;

    const title =
        manga.attributes.title.en ??
        manga.attributes.altTitles?.filter((altTitle) => altTitle.en)[0]?.en ??
        manga.attributes.title["ja-ro"] ??
        manga.attributes.title["ja"] ??
        "Unknown Title";

    return {
        title: `${title} | Hanami Manga`,
    };
}

export default function MangaPage({ params }: Props) {
    return (
        <Suspense fallback={<MangaPageSkeleton />}>
            <MangaContent params={params} />
        </Suspense>
    );
}

export async function MangaContent({ params }: Props) {
    const chaptersPerPage = 12;

    const { data: manga } = (await fetch(
        `${BASE_URL}api/proxy/manga/${params.uuid}?includes[]=cover_art`,
        { next: { revalidate: 60 * 60 } },
    ).then((response) => response.json())) as MangaResponseSchema;

    const relationshipAttributes = manga.relationships.find(
        (relationship) => relationship.type === "cover_art",
    )?.attributes as { fileName?: string } | null;

    const title =
        manga.attributes.title.en ??
        manga.attributes.altTitles?.filter((altTitle) => altTitle.en)[0]?.en ??
        manga.attributes.title["ja-ro"] ??
        manga.attributes.title["ja"] ??
        "Unknown Title";

    const description =
        manga.attributes.description.en ?? "No description available.";

    const tags = manga.attributes.tags;

    return (
        <div className="my-8 px-4 lg:container mx-auto">
            <div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto">
                <Image
                    src={`/api/proxy/proxyimage?url=https://mangadex.org/covers/${manga.id}/${relationshipAttributes?.fileName}`}
                    alt="Manga Cover"
                    width={400}
                    height={600}
                    className="w-full max-w-[300px] h-fit md:max-w-none rounded-lg shadow-lg"
                    style={{ aspectRatio: "400/600", objectFit: "cover" }}
                />
                <div className="space-y-4">
                    <h1 className="text-4xl font-bold">{title}</h1>
                    <Tags tags={tags} />
                    <p className="text-muted-foreground">{description}</p>
                    <div className="flex items-center gap-4">
                        <Button>
                            <Link href="#">Read Now</Link>
                        </Button>
                        <Button>
                            <Link href="#">Add to Favorites</Link>
                        </Button>
                    </div>
                    <ChapterList
                        chaptersPerPage={chaptersPerPage}
                        mangaId={params.uuid}
                    />
                </div>
            </div>
        </div>
    );
}
