// src/components/footer.svelte
<footer class="bg-black px-6 py-6 text-white md:px-10 dark:bg-gray-800">
	<div class="container mx-auto flex items-center justify-between">
		<p class="text-sm">© 2024 hanamimanga. All rights reserved.</p>
		<p>
			Check out <a class="font-bold text-blue-400" href="https://anime.lapaii.dev/" target="_blank"
				>mikanime</a
			>, the anime version of this website!
		</p>
		<nav class="flex items-center gap-4">
			<a class="hover:underline" href="/about"> About </a>
			<a class="hover:underline" href="/contact"> Contact </a>
			<a class="hover:underline" target="_blank" href="https://github.com/yorunoken/hanamimanga">
				GitHub
			</a>
		</nav>
	</div>
</footer>

// src/components/footer.tsx
import { Button, Input } from "@chakra-ui/react";
import Link from "next/link";

export default function Footer() {
    return (
        <footer className="bg-[#1e1e1e] text-white flex items-center justify-between px-6 py-3">
            <div className="font-bold text-sm">
                © 2024 hanamimanga. All rights reserved.
            </div>
            <Link
                href="https://anime.lapaii.dev"
                target="_blank"
                className="text-sm font-medium hover:underline"
                prefetch={false}
            >
                Check out mikanime, the anime version of this website!
            </Link>
            <nav className="flex items-center gap-4 text-sm">
                <Link href="#" className="hover:underline" prefetch={false}>
                    About
                </Link>
                <Link href="#" className="hover:underline" prefetch={false}>
                    Contact
                </Link>
                <Link href="#" className="hover:underline" prefetch={false}>
                    GitHub
                </Link>
            </nav>
        </footer>
    );
}

function ClipboardIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
            <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
        </svg>
    );
}

function ClockIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="12" cy="12" r="10" />
            <polyline points="12 6 12 12 16 14" />
        </svg>
    );
}

function HeartIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
        </svg>
    );
}

function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.3-4.3" />
        </svg>
    );
}
